default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'password' %>
  database: <%= ENV['DATABASE_NAME'] || 'mydatabase' %>
  # host is set per-environment below

development:
  <<: *default
  host: db
  database: mydatabase

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  database: checkmate_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails_user
  password: <%= ENV['DB_PASSWORD'] %>
  database: tag_app_production
  host: /cloudsql/capstone-tool-assisted-grading:us-central1:tag-app-db